src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VideoRepository::class)]
class Video
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\ManyToOne(targetEntity: Category::class)]
    private $category;

    #[ORM\Column(type: 'string', length: 255)]
    private $youtube_id;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCategoryId()
    {
        return $this->category;
    }

    public function setCategoryId(int $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getYoutubeId(): ?string
    {
        return $this->youtube_id;
    }

    public function setYoutubeId(string $youtube_id): self
    {
        $this->youtube_id = $youtube_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VideoController extends AbstractController
{
    #[Route('/show_videos', name: 'show_videos')]
    public function showVideos(ManagerRegistry $doctrine): Response
    {
        // query with join from entity Video
//        $showVideos = $doctrine
//            ->getRepository(Video::class)
//            ->findAll();

        // query with custom join
        $showVideos = $doctrine
            ->getRepository(Video::class)
            ->findAllWithCategories();
        return $this->render('video/showVideos.html.twig', [
            'showVideos' => $showVideos,
        ]);
    }

    #[Route('/show_video/{youtube_id}', name: 'show_video')]
    public function showOneVideo($youtube_id, ManagerRegistry $doctrine): Response
    {
        $video = $doctrine
            ->getRepository(Video::class)
            ->findBy([
                'youtube_id' => $youtube_id
            ]);
        return $this->render('video/showOneVideo.html.twig', [
            'video' => $video[0],
        ]);
    }

    #[Route('/add_video', name: 'add_video')]
    public function addVideo(): Response
    {
        return $this->render('video/addVideo.html.twig', [
        ]);
    }

//    #[Route('/show_video_by_category/{category_id}',
//        name: 'show_video_by_category')
//    ]
    /**
     * @Route("/show_video_by_category/{category_id}",
     *      name="show_video_by_category",
     *      requirements={"category_id"="\d+"})
     */
    public function showByCategory(int $category_id, ManagerRegistry $doctrine): Response
    {
        // query from this method
//        $videoByCategory = $doctrine
//            ->getRepository(Video::class)
//            ->findBy([
//                'category' => $category_id
//            ], [
//                'title' => 'ASC'
//            ]);
        // query from Videorepository
        $videoByCategory = $doctrine
            ->getRepository(Video::class)
            ->findByCategory($category_id);
        return $this->render('video/showVideos.html.twig', [
            'showVideos' => $videoByCategory,
        ]);
    }
}

templates/video/addVideo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Video!{% endblock %}

{% block body %}
    <div>
        <h3>Add Video</h3>
    </div>
{% endblock %}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video!{% endblock %}

{% block body %}
    <div>
        <h3>Video</h3>
    </div>
{% endblock %}

templates/video/showOneVideo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video!{% endblock %}

{% block body %}
    <h3>
        <a href="{{ path('show_videos') }}">
            &#8592; Show All Videos
        </a>
    </h3>
    <h3>{{ video.title }}</h3>
    <div class="grid">
        <div class="grid_item">
            <iframe width="840"
                    height="430"
                    src="https://www.youtube.com/embed/{{ video.youtubeId }}">
            </iframe>
        </div>
    </div>
{% endblock %}

templates/video/showVideos.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video!{% endblock %}

{% block body %}

    <h3>My Videos</h3>
    <div class="grid">
        {% for video in  showVideos %}
            <div class="grid_item">
                <h3>
                    <a href="{{ path('show_video', {'youtube_id' : video.youtubeId}) }}">
                        {{ video.title }}
                    </a>
                </h3>

                <h3> {{ video.getCategoryId.title }}</h3>

                <iframe width="420"
                        height="315"
                        src="https://www.youtube.com/embed/{{ video.youtubeId }}">
                </iframe>
            </div>
        {% endfor %}
    </div>
{% endblock %}